s = set()
d = input("enter the values:")
s.add(int(d))
d = input("enter the values:")
s.add(int(d))
d = input("enter the values:")
s.add(int(d))
d = input("enter the values:")
s.add(int(d))
d = input("enter the values:")
s.add(int(d))
d = input("enter the values:")
s.add(int(d))
d = input("enter the values:")
s.add(int(d))

print(s)
